In [2]:
import numpy as np

In [6]:
arr = np.arange(-3, 5)
arr%2==0

array([False,  True, False,  True, False,  True, False,  True])

In [8]:
rand = np.random.RandomState(0)
x = rand.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [12]:
x[x>4]

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [27]:
(x > 0) & (x % 2 == 0)

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True, False,  True]])

In [28]:

np.where((x > 0) & (x % 2 == 0))

(array([2, 2, 2]), array([0, 1, 3]))

In [23]:
np.where(arr % 2 == 0)

(array([1, 3, 5, 7]),)

In [24]:
type((x%2==0))

numpy.ndarray