In [36]:
import numpy as np

In [37]:
# 1. Create a vector with values ranging from 10 to 49
vec = np.arange(10, 50, 1, dtype=int)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [38]:
# Create a 3x3 matrix with values ranging from 0 to 8.
mat = np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
# Create a 3x3 identity matrix.

identity_matrix = np.eye(3, dtype=int)
identity_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [40]:
# Create a 3x3x3 array with random values.

rng = np.random.default_rng()
random_array = rng.random(size=(3, 3, 3))
random_array

array([[[0.28475057, 0.39386075, 0.30252722],
        [0.20930306, 0.39763963, 0.83831924],
        [0.99702431, 0.12169027, 0.13818148]],

       [[0.49147094, 0.2140425 , 0.05709769],
        [0.41622004, 0.98634306, 0.36959432],
        [0.20894807, 0.35918416, 0.38879189]],

       [[0.41612942, 0.47663465, 0.79882913],
        [0.75298808, 0.29112452, 0.5601952 ],
        [0.34770092, 0.70789858, 0.1340588 ]]])

In [41]:
# Create a 10x10 array with random values and find the minimum and maximum values.

random_array = rng.random(size=(10, 10))
max_of_matrix = random_array.max()
min_of_matrix = random_array.min()
print("max = ", max_of_matrix)
print("min = ", min_of_matrix)

max =  0.9909128946869165
min =  0.012313703082436733


In [42]:
# Create a random vector of size 30 and find the mean value.
rand_vec = rng.random(30)
mean = rand_vec.mean()
mean

np.float64(0.5354781857211333)

In [43]:
# Normalize a 5x5 random matrix.
# method-1
rand_matrix = rng.random(size=(5,5))
min = rand_matrix.min()
max = rand_matrix.max()
normalized_matrix = (rand_matrix-min)/(max-min)
normalized_matrix


array([[0.97395087, 0.0959266 , 0.98885219, 0.65042901, 0.88742454],
       [0.51814276, 0.15686294, 0.41426107, 0.3394667 , 0.78834633],
       [0.60433677, 0.73241268, 0.21450857, 0.86759896, 0.        ],
       [0.22509542, 0.49705636, 0.7701828 , 0.34686703, 1.        ],
       [0.82882762, 0.77380261, 0.11846876, 0.451398  , 0.41039063]])

In [44]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12],
              [13, 14, 15]])

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])

np.dot(A, B)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

In [45]:
# Create two 3x3 matrices and compute their dot product.

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

np.dot(A, B)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [46]:
# Given a 4x4 matrix, find its transpose.

C = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
C.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [47]:
# Create a 3x3 matrix and calculate its determinant.
D = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

np.linalg.det(D)

np.float64(0.0)

In [48]:
# Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

np.dot(A, B)

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [49]:
# Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.

E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([1, 2, 3])

np.dot(E, v)

array([14, 32, 50])

In [50]:
# Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.


A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

b = np.array([14, 32, 50])


x = np.linalg.solve(A, b)
print(x)

[-2.0000000e+00  8.0000000e+00 -8.8817842e-16]


In [51]:
# Given a 5x5 matrix, find the row-wise and column-wise sums.

F = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

# Compute row-wise sum
row_sums = np.sum(F, axis=1)

# Compute column-wise sum
column_sums = np.sum(F, axis=0)

print("Row-wise sums:", row_sums)
print("Column-wise sums:", column_sums)

Row-wise sums: [ 15  40  65  90 115]
Column-wise sums: [55 60 65 70 75]
